### ISSUE TITLE
单个执行用例，异常，麻烦大佬有时间帮忙分析一下

### ISSUE THREAD

**Issue by wangdahua28** [jianbing/utx#2]
操作就是单个执行unittest中的TestCase

Traceback (most recent call last):
  File "C:\Python36\Lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Python36\Lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Python36\Lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
  File "C:\Python36\Lib\unittest\loader.py", line 168, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: type object 'ReadingProcess' has no attribute 'test_createTask'

**Comment by jianbing** [comment]
看下demo文件夹下的 stop_patch_example.py，里边有例子
